### ISSUE TITLE
IPFS Integration

### ISSUE THREAD

**Issue by r0kk3rz** [berkmancenter/amber_common#30]
Wow, what a great initiative!

One thing that would make Amber super powerful would be integration with something like [IPFS](https://ipfs.io/), the link will explain it better than I can, but you can think of it as a distributed file system of sorts.

What this means for Amber is that if multiple Amber enabled sites have the same broken link, they can help each other out keeping that link alive, as well as transparently copy the backed up content between sites should another website want to link to the same no-longer-available content.

Keeping linked content available is a core idea behind the IPFS project, so check it out

**Comment by genevec** [comment]
We would love that. It would be great to shard out content preserved by Amber. Berkman sees Amber as a very early introduction to addressing the problem of distributed content, with a focus on accessibility. If you have a connection to IPFS, we'd love to talk more with them!
