### ISSUE TITLE
Support for Jekyll? (or static site generators more broadly)

### ISSUE THREAD

**Issue by michaelstepner** [berkmancenter/amber_common#36]
Hello! I'm wondering if building a plugin for Jekyll (or other static site generators) is part of the roadmap for Amber.  I'm entirely sympathetic to the fact that you have limited resources and it makes sense to target the biggest CMS platforms. But I'd love to see a tool that helps a static site generator preserve external links.

I imagine that the plugin could check every external link at build time, see if it already has a cached copy, and if not, cache one. Automatic failover to the cached page using client-side javascript would be a nice-to-have. But even if, after a link died, the owner of the static page had to manually edit the link to point to the cached copy (which they have because it was cached long ago when the link was first added to the site), the plugin would be very useful.  It would automatically ensure that the required cache is available.

One of my reasons for choosing a static site generator over a CMS is for the long-term preservation of _my website_. I know my static site will exist in its current form as long as I keep it online, without worrying about security vulnerabilities, updates, patches, etc.  It would be wonderful to truly preserve the site, with all its external links intact.

**Comment by genevec** [comment]
Hi! Unfortunately the Berkman Center doesn't have plans to build a plugin for Jekyll right now. I also love the idea of static site generators for the reasons you outline, and your implementation sounds right for how Amber might work with one. Our Drupal module and WordPress plugin are written in PHP, which makes porting to Ruby a little more difficult than, say, to another PHP-based CMS. And the whole no-databases-thing with static site generators would mean we'd have to rethink and simplify a few things in the existing workflow. (Which would probably be a good process.)

However! We'd certainly welcome anyone who wanted to contribute to our codebase and write a Jekyll plugin. And we'd be happy to offer insight during development. I know this isn't ideal, but it's the best we can offer at the moment. Maybe you are, or know, a Ruby dev who has been burdened by link rot and would be up to the challenge? :-)

**Comment by michaelstepner** [comment]
Totally understandable!  Unfortunately I'm an economist, not a ruby dev :-) But perhaps someone else will come along and take up the mantle.

In the meantime, I'm using another berkproject and manually preserving my most important links using [Perma](https://perma.cc).  I'm really glad you and your colleagues are developing these tools!

**Comment by michaelstepner** [comment]
I couldn't resist looking into it a bit more, despite having zero Ruby under my belt. I discovered the [web-page-archiver gem](http://murb.github.io/web-page-archiver/), installed it, and tested it interactively on a couple links.  It worked nicely!

It seems like it would be a pretty tractable project for a Ruby developer to write a Jekyll plugin that:
1. Detects all the external links in a site at build-time
2. Checks if they've been archived
3. Runs `web-page-archiver` on unarchived pages

If there is someone on your team or a friend of your team who knows Ruby, perhaps they'll consider giving it a shot!  I'll try my hand at a potential spec for how these archived pages could be stored:
- an `_amber/` folder in the root of the static site
- a subfolder for each domain that has an archived page
  - `_amber/github.com/`
  - `_amber/amberlink.org/`
  - etc.
- an HTML file for each archived page
  - This is the part with tricky decisions about how to store uniquely.
  - maybe just replicate the directory tree of the site being archived?
    - For example, `https://cyber.law.harvard.edu/publications/2016/managing_user_rights` could be saved to `_amber/cyber.law.harvard.edu/publications/2016/managing_user_rights.html`

**Comment by genevec** [comment]
So, so awesome. Thank you!
