### ISSUE TITLE
Dev site for amberpc

### ISSUE THREAD

**Issue by ryanttb** [berkmancenter/amber_common#9]
* **Issue**: Can we get one?

**Comment by genevec** [comment]
Hey Ryan! We should have one by 7/27, but you may be able to deploy on India?

**Comment by genevec** [comment]
PS this works. :+1:

**Comment by ryanttb** [comment]
That's a PHP server, we'll have to wait for JSD to make a dev rails environment for us. I put some screenshots in Redmine though.
